- name: Event driven ansible test
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Test
      condition: event.payload.something == "hello"
      action:
        debug:
          msg: "rule is triggered TESTTT"
