- name: Event driven ansible test
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    # - name: Test
    #   condition: event.payload.something == "hello"
    #   action:
    #     debug:
    #       msg: "rule is triggered TESTTT"
    #
    # - name: Debug
    #   condition: event.payload.something == "hello"
    #   action:
    #     debug:
    #       msg: "event data: {{ event }}"

    - name: run job template
      condition: event.payload.something == "hello"
      action:

        - name: Run template
          run_job_template:
          name: ping
          organization: Default

        - name: Debug
          debug:
            msg: "event var: {{ event }}"
